### ISSUE TITLE
Any hopes of seeing a GNU/Linux version of this?

### ISSUE THREAD

**Issue by vanfanel** [henrikstengaard/hst-amiga#2]
Hi!

These Amiga tools seem very useful, and as far as I know we don't have any means to format a PFS3 partition in GNU/Linux.

So, is it possible to have a commandline version of these tools for building on GNU/Linux?

Thanks!

**Comment by henrikstengaard** [comment]
Hi,

It sure is very useful being able to format a PFS3 partition without having to start an Amiga emulator. This repo represents a C# library with classes to read and write various Amiga partitions, filesystems, which is published both here under releases and at nuget.org. So it requires .NET programming in order to use it and if used with .NET Core, it can run on Windows, macOS and Linux with a x86/x64/arm64 cpu.

Take a look at my disk imaging tool at https://github.com/henrikstengaard/hst-imager, which uses this library to partition and format Amiga disks and is released as ready to use standalone binaries for Windows, macOS and Linux.

The CLI version is currently the most complete and GUI version is slowly getting same features implemented. Both under development.

**Comment by henrikstengaard** [comment]
In any case, please give more details about your Linux environment should Hst Imager not work out of the box, so I can update it with better support for Linux.

**Comment by vanfanel** [comment]
@henrikstengaard Ah, thanks a lot! https://github.com/henrikstengaard/hst-imager does the work perfectly here on aarch64 and x86_64!

Indeed, formatting without having to resort to an emulator is great!
